runtime: nodejs20
service: default
instance_class: F1

liveness_check:
  path: /api/health-check
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  initial_delay_sec: 10

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

automatic_scaling:
  min_instances: 1
  max_instances: 1
